"""your message

Revision ID: e4f9054ecf66
Revises: 1964b7bf6523
Create Date: 2025-06-21 11:31:44.949206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f9054ecf66'
down_revision = '1964b7bf6523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
