"""Add content and username columns to Message

Revision ID: ea332978e281
Revises: e4f9054ecf66
Create Date: 2025-06-21 15:57:11.506298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea332978e281'
down_revision = 'e4f9054ecf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.String(), nullable=False))
    op.add_column('messages', sa.Column('username', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'username')
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
